version: '3.0'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=sawitprodb
    ports:
      - '5432:5432'
    volumes:
      - my-db-sawit-pro:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  my-db-sawit-pro: